___

# Machine Learning in Geosciences ] 
Department of Applied Geoinformatics and Carthography, Charles University

Lukas Brodsky lukas.brodsky@natur.cuni.cz


### PyTorch installation

`pip install torch`
`pip install torchvision`

### PyTorch tensor

Tensors are the building blocks for representing data in PyThorch. It is the fundamental data structure. The term `tensor` comes bundled with the notion of spaces. In this context of deep learning, tensors refer to the generalization of vectors and matrices to an arbitrary number of dimensions. 

The torch package contains not only the data structures for **multi-dimensional arrays** but also defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

### PyTorch tensor vs. NumPy array

If you're familiar with NumPy arrays, transitioning to PyTorch tensors is smooth—many operations are conceptually and syntactically similar. However, PyTorch brings additional power, especially for deep learning and GPU-accelerated computations.

What is the difference between numpy array and pytorch tensor?

1. The numpy arrays are the core functionality of the numpy package designed to support faster mathematical operations. Pytorch tensors are similar to numpy arrays, but can also be operated on CUDA-capable Nvidia GPU.
   
   
2. Numpy arrays are mainly used in typical machine learning algorithms. Pytorch tensors are mainly used in deep learning which requires heavy matrix computation.

3. Unlike numpy arrays, while creating pytorch tensor, it also accepts two other arguments called the device_type (whether the computation happens on CPU or GPU) and the requires_grad (which is used to compute the derivatives).

#### PyTorch API

The PyTorch API establish a few directions on where to find things in the documentation (https://pytorch.org/docs/stable/index.html). 

## What’s the Same? 
### PyTorch vs. NumPy
**Syntax and behavior**: PyTorch tensors and NumPy arrays share similar syntax for indexing, slicing, reshaping, broadcasting, element-wise operations, and reductions (e.g., sum, mean, max).

In [1]:
import torch 
import numpy as np

In [2]:
a_np = np.array([[1, 2], [3, 4]])
a_torch = torch.tensor([[1, 2], [3, 4]])

In [3]:
# Both support slicing
print(a_np[:, 0])        # [1 3]
print(a_torch[:, 0])     # tensor([1, 3])

[1 3]
tensor([1, 3])


In [4]:
# Zeros and ones
np_zeros = np.zeros((2, 3))
torch_zeros = torch.zeros((2, 3))

In [5]:
np_ones = np.ones((2, 3))
torch_ones = torch.ones((2, 3))

In [6]:
# Identity matrix
np_eye = np.eye(3)
torch_eye = torch.eye(3)

In [7]:
# Shape and Reshaping
# Shape attribute
print(a_np.shape)       # (2, 2)
print(a_torch.shape)   # torch.Size([2, 2])

(2, 2)
torch.Size([2, 2])


### Data types and shapes: 
both support multiple data types (float32, int64, etc.) and n-dimensional arrays (tensors) with shape attributes.

### Interoperability: 
PyTorch and NumPy arrays can be converted back and forth easily (when on CPU):

**torch.from_numpy()**

**a_torch.numpy()**

In [8]:
a_np = np.array([1, 2, 3])
a_torch = torch.from_numpy(a_np)  # Shares memory!
a_np_back = a_torch.numpy()

## What’s Similar?

**Broadcasting rules**: PyTorch follows NumPy-style broadcasting rules for arithmetic between arrays of different shapes.

**Linear algebra operations**: Both provide high-level APIs for matrix multiplication (@ or .matmul()), dot product, transposition, etc.

**Random number generation**: Both libraries offer similar random sampling utilities (though APIs differ slightly).

### Broadcasting 
is a technique that allows arrays (or tensors) of different shapes to be used in arithmetic operations without explicit replication. It's like virtually expanding the smaller array to match the shape of the larger one.

**When operating on two tensors:**

**1. Right-align the shapes.**

`
A: (3, 1, 5)
B: (   1, 5)   ← B is treated as (1, 1, 5)

`

**2. Dimensions must match or be 1 (which means that dimension can be broadcast).**
`

A.shape = (4, 1, 6)

B.shape = (1, 5, 6)

dim 1: 4 vs 1 → ok, broadcast B

dim 2: 1 vs 5 → ok, broadcast A

dim 3: 6 vs 6 → ok, match

C = A + B

print(C.shape)  # torch.Size([4, 5, 6])

`

`
A.shape = (2, 3)

B.shape = (4, 3)

dim 1: 2 vs 4 → NOK, Not equal, neither is 1 → Error

dim 2: 3 vs 3 → Ok

`

**3. If a dimension doesn't exist (because one tensor has fewer dimensions), it’s treated as 1.** 
`
A.shape = (3, 4, 5)

B.shape =      (4, 5)

3 vs 1 → ok, broadcast

4 vs 4 → ok

5 vs 5 → ok

A = torch.randn(3, 4, 5)

B = torch.randn(4, 5)

C = A + B  # Broadcasts B to (3, 4, 5)

print(C.shape)  # torch.Size([3, 4, 5])

`

In [9]:
# Adding a scalar
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = 10.0

print(a + b)
# tensor([[11., 12.],
#         [13., 14.]])

tensor([[11., 12.],
        [13., 14.]])


In [10]:
#  2D + 1D
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([10.0, 20.0])  # Shape: (2,)

print(a + b)
# tensor([[11., 22.],
#         [13., 24.]])

tensor([[11., 22.],
        [13., 24.]])


In [11]:
# Incompatible shapes
a = torch.ones(3, 4)
b = torch.ones(5, 1)

# This will raise an error:
# print(a + b)

In [12]:
# In PyTorch (like NumPy), broadcasting only works when shapes can be aligned 
# and broadcasted according to the rules!!! 

In [13]:
# 3D tensor broadcasting
a = torch.rand(1, 3, 1)  # Shape: (1, 3, 1)
b = torch.rand(2, 1, 4)  # Shape: (2, 1, 4)

# Broadcast result will be shape (2, 3, 4)
c = a + b
print(c.shape)  # torch.Size([2, 3, 4])

torch.Size([2, 3, 4])


In [14]:
# Math Operations
a_np = np.array([1, 2, 3])
a_torch = torch.tensor([1, 2, 3])

# Element-wise addition
print(a_np + 1)       # [2 3 4]
print(a_torch + 1)    # tensor([2, 3, 4])

[2 3 4]
tensor([2, 3, 4])


In [15]:
# Element-wise multiplication
print(a_np * 2)       # [2 4 6]
print(a_torch * 2)    # tensor([2, 4, 6])

[2 4 6]
tensor([2, 4, 6])


In [16]:
# Dot product
print(np.dot(a_np, a_np))       # 14
print(torch.dot(a_torch, a_torch))  # tensor(14)

14
tensor(14)


In [17]:
# Matrix multiplication
mat_np = np.array([[1, 2], [3, 4]])
mat_torch = torch.tensor([[1, 2], [3, 4]])

print(mat_np @ mat_np)             # [[ 7 10] [15 22]]
print(torch.matmul(mat_torch, mat_torch))  # same result

[[ 7 10]
 [15 22]]
tensor([[ 7, 10],
        [15, 22]])


In [18]:
# Random values
np_random = np.random.rand(2, 3)
torch_random = torch.rand(2, 3)  # Uniform [0, 1)

## What’s Different?

**PyTorch:**

* GPU support: `.to("cuda")`
* Autograd: `requires_grad=True`
* Deep learning native: Integrated with models, optimizers, loss functions
* In-place ops: Many functions end with _ (e.g., add_()) for memory efficiency
* Memory sharing: Tensor and NumPy can share memory (CPU only)


In [ ]:
# Example of GPU usage:
# a = torch.tensor([1.0, 2.0], device='cuda')  # Runs on GPU
a = torch.tensor([1.0, 2.0], device="")  # Runs on CPU

In [22]:
# Example of enabling gradient tracking:
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x
y.backward()
print(x.grad)  # Computes dy/dx

tensor([7.])
